### ISSUE TITLE
paths 

### ISSUE THREAD

**Issue by mauriciodulce** [jimblue/statamic-addon-webpacker-hub#4]
How do I change the routes of the NPM package, is my installation different from the default CMS?

**Comment by jimblue** [comment]
Hello @mauriciodulce,

Why do you want to change the routes of the NPM packages?
Can you explain me a bit more what the context and you goal?

Thank you

**Comment by jimblue** [comment]
Also please give this issue a clear name. **paths** doesn't help ;)

**Comment by mauriciodulce** [comment]
- To run the plugin you must have the default installation of the CMS, I have the public folder in the webroot of the site, the other folders are not accessible.

```
Statamic Site    
│
└───local
│   
└───public
│   │   index.php
│   │   
│   └─── _assets
│   │       │____container_folrders_images   
│   |       │____container_folrders_images
│   |       │____container_folrders_images
|   |
|   |
|   |___ theme_assets
│           │____javascripts
|           |       main.js
|           |       plugins.js
|           |       vendors.js
│           │____stylesheets
|           |       main.css
|           |
│           │____images
|                      ...        
└───site
│   │   
│   │   
│   └─── addons
|   |       |_ ..
|   |
│   └─── database
|   |       |_ ..
|   |
│   └─── helpers
|   |       |_ ..
|   |
│   └─── lang
|   |
│   └─── settings
|   |       |_ ..
|   |
│   └─── test
|
|
└───statamic
|
|
└───storage
│   │   
│   │   
│   └─── addons
|   |       |_ ..
|   |
│   └─── content
|   |       |_ ..
|   |
│   └─── forms
|   |       |_ ..
|   |
│   └─── users
|
|
|__ themes
    |
    |___ theme_name
            |
            |    meta.yaml
            |___ layouts
            |
            |___ partials
            | 
            |___ settings
            |
            |___ templates
|__ node_modules
|
|__ resources
|       |
|       |__ images
|       |__ javascripts
|       |__ scss
|       |__ fonts
|       |__ svg
|
| package.json
| please
| babel.config.js
| postcss.config.js
| prettier.config.js
| stylelint.config.js
| webpack.config.js

```




Another problem is that after following the installation documentation where only the local domain must be defined, When running the development command these errors come out.

npm run webpacker:dev

```

> @ webpacker:dev /Users/usersystem/webdev/sites/usersystem/site/themes/name_theme
> cross-env NODE_ENV=development node webpack.config.js

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at new Settings (/Users/usersystem/webdev/sites/usersystem/site/themes/name_theme/node_modules/statamic-addon-webpacker/app/settings.js:49:30)
    at webpacker (/Users/usersystem/webdev/sites/usersystem/site/themes/name_theme/node_modules/statamic-addon-webpacker/app/index.js:6:21)
    at Object.<anonymous> (/Users/usersystem/webdev/sites/usersystem/site/themes/name_theme/webpack.config.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ webpacker:dev: `cross-env NODE_ENV=development node webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ webpacker:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/usersystem/.npm/_logs/2019-11-29T22_53_55_017Z-debug.log
```
So I must define the variable within 

**development.yaml**
`context_folder: resources`

###  Attempt 2
`npm run webpacker:dev`
```
@ webpacker:dev /Users/usersystem/webdev/sites/usersystem/site/themes/name_theme
> cross-env NODE_ENV=development node webpack.config.js

/Users/usersystem/webdev/sites/usersystem/site/themes/name_theme/node_modules/statamic-addon-webpacker/app/settings.js:56
    const statamicEnvironment = dotEnv.config({ path: dotEnvPath }).parsed.APP_ENV || 'production'
                                                                          ^

TypeError: Cannot read property 'APP_ENV' of undefined
    at new Settings (/Users/usersystem/webdev/sites/usersystem/site/themes/name_theme/node_modules/statamic-addon-webpacker/app/settings.js:56:75)
    at webpacker (/Users/usersystem/webdev/sites/usersystem/site/themes/name_theme/node_modules/statamic-addon-webpacker/app/index.js:6:21)
    at Object.<anonymous> (/Users/usersystem/webdev/sites/usersystem/site/themes/name_theme/webpack.config.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ webpacker:dev: `cross-env NODE_ENV=development node webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ webpacker:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
I never use that file, since I define everything in the .env file
But to test the plugin, I created the file

### Third attempt
`npm run webpacker:dev`

The task run ok.  
 DONE  Compiled successfully in 14213ms 
 I  Your Statamic theme  is ready for development: http://localhost:3001

 
 Change the {{theme}} tags to {{webpacker}}

 and I have a error `webpacker.json does not exist``

The other point is that when an scss or css file is updated, the files are not generated and the changes are not updated

**Comment by jimblue** [comment]
Solved now, as discussed on Discord.
Cheers man 😄
